# Generated by Django 3.1.4 on 2021-01-11 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('start_destination', models.CharField(max_length=250)),
                ('stop_destination', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('ticket_id', models.CharField(default='', max_length=500, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReserverdTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateTimeField(auto_created=True, auto_now=True)),
                ('order_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
